sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: os.getenv("endpoint")

    access-key-id: os.getenv("access-key-id")

    access-key-secret: os.getenv("access-key-secret")

    bucket-name: os.getenv("bucket-name")

